# Generated by Django 4.0.8 on 2023-03-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_courses_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='titel',
            new_name='title',
        ),
    ]
